Remove `int64#`, `int32#`, `nativeint#`, and `float32#` (#6663)
These types are not "true" unboxed versions as they are boxed as custom
blocks, so we remove them to restore the boxing invariant.

Instead of these types, we use `int64_u`, `int32_u`, `nativeint_u`, and
`float32_u`, added in https://github.com/oxcaml/oxcaml/pull/6321 and
https://github.com/oxcaml/oxcaml/pull/6459. We add hints pointing to
these types when one tries to reference a deleted unboxed version:
```
type t = int64#
         ^^^^^^
Error: The type "int64" has no unboxed version.
Hint: Did you mean "int64_u"?
```

Note that `int64` and `int64_u box` etc. are now distinct types. The
former is represented as a custom block, while the latter won't be once
`%box` is implemented (`int64_u box` and `nativeint_u box` will be
no-scan mixed blocks and `int32_u box` and `float32_u box` will be
`immediate64`s).

Primitive type names are unchanged (e.g.
`%array_safe_get_indexed_by_int32#`). In the future, we may allow
multiple spellings so we can migrate to spellings matching the new
predef types.

Finally, we add one to the cost of the paths of `int64_u`, etc.,
matching the costs of the removed unboxed versions. This is pretty ugly,
but notably reduces error message churn in our internal codebase.

### Review
- Review all non-testsuite changes as normal.
- In the testsuite, these are the files with manual (as in, not just via
`sed`, but still mostly uninteresting) changes:
  * `testsuite/tests/typing-layouts-box/box.ml`
  * `testsuite/tests/typing-layouts/hash_types.ml`
  * `testsuite/tests/typing-layouts/generate_stringlike_indexing.ml`
  * `testsuite/tests/typing-layouts/renamed_unboxed_numbers.ml`
  * `testsuite/tests/typing-layouts-bits32/parsing.ml` (deleted)
  * `testsuite/tests/typing-layouts-bits64/parsing.ml` (deleted)
  * `testsuite/tests/typing-layouts-float32/parsing.ml` (deleted)
  * `testsuite/tests/typing-layouts-word/parsing.ml` (deleted)
- Note that OxMirror will not pass until a tree smash completes
internally, but this change already compiles with that tree smash - see
internal chat.