Fix to Const.comonadic_to_monadic_min (#6244)
The current definition of `Value_with.Const.comonadic_to_monadic_min` is
defined as `C.Core_morph.comonadic_to_monadic_min`, which is incorrect.

`C.Core_morph.comonadic_to_monadic_min` is the morphism used in the
solver, and its direction is thus flipped (its signature goes to
`Monadic_op.t`). The correct implementation of the user-facing morphism
is to "flip it twice" and use `C.Core_morph.comonadic_to_monadic_max`
(as it is done in `Value_with.comonadic_to_monadic_min`).

```
The bug leads to the following program not type checking: 
let f (x @ static) =
  for _i = 0 to 0 do
    let _ @ static = x in
    ()
  done
File "test.ml", line 3, characters 21-22:
3 |     let _ @ static = x in
                         ^
Error: This value is dynamic
         because it is used in a loop (at file "test.ml", lines 2-5, characters 2-6).
       However, the highlighted expression is expected to be static.
```

To avoid confusion in the future, this PR renames all morphisms defined
in `Lattices_mono` (and thus used in the solver) as `monadic_op` rather
than `monadic`.

A regression test has been added to `staticity.ml`.