fix: Pprintast incorrectly prints exclave-of-seq (#7416)
**`(exclave_ ()); ()` prints as `exclave_ (); ()` which parses as
`exclave_ ((); ())`**

`exclave_` and `_; _` have tricky precedence; e.g. the first two of
these parse to identical representations, whereas the third does not:
```
let no_parens () = exclave_ (); ()
[%%expect{|
val no_parens : unit -> unit @ local = <fun>
|}]
let right_parens () = exclave_ ((); ())
[%%expect{|
val right_parens : unit -> unit @ local = <fun>
|}]
let left_parens () = (exclave_ ()); ()
[%%expect{|
Line 1, characters 21-34:
1 | let left_parens () = (exclave_ ()); ()
                         ^^^^^^^^^^^^^
Error: Exclave expression should only be in tail position of the current region.
|}]
```
Pprintast seems to think this is the other way around: it deletes
parentheses from `(exclave_ ()); ()` to produce `exclave_ (); ()`, which
does not round-trip. Added a regression test to the end of
`testsuite/tests/parsetree/source_jane_street.ml`.

(Alternatively, is this `;` behavior unexpected to `exclave_` power
users? Should it be the other way 'round?)