Support generalized sort variables in primitive applications (#7243)
Previously, primitives (even those annotated with `[@layout_poly]`)
could not be applied to types whose sorts contain generalized variables.
This stops us from writing something like the layout-polymorphic
identity primitive:

```ocaml
external[@layout_poly] identity : ('a : any). 'a -> 'a = "%identity"
let poly_ f x = identity x

(*
$ ocamlopt -extension-universe alpha lpoly.ml
>> Fatal error: layout_of_const_sort: unexpected genvar
Fatal error: exception Misc.Fatal_error
*)
```

This PR allows generalized sort variables in primitive applications. The
core change is just one line, but some extra work was needed to update
the `%set_idx` primitives, which are weird in that they have special
logic to try and recover scannable axes/externality bounds and skip
`caml_modify` if appropriate. Fortunately we can repurpose a helper I
introduced in #7152.

In a follow-up, I also added an explicit "lpoly argument not supported"
error for the `Peek` and `Poke` primitives, which need some additional
work to support lpoly arguments. (See the CR comment.)

Resolves internal ticket 7187.

### For reviewers
Commit structure should be helpful.