Change the reporting of mode errors during subsumption (#6227)
When the modes of an implementation are not more general than the modes
of a module signature, the current error reporting only prints the
mismatching signatures. This can lead to confusing error messages when
the mode at fault does not get printed, such as when it is implied by
other modes.

For instance, the following error message never prints or mentions the
`yielding` mode, which is the mode at fault:
```
module M : sig
  val with_ : f:('a -> 'a) @ local -> unit

end = struct
  let with_ ~f =
    let (use_f @ local unyielding) x =
      f x
    in
    let _ = use_f in
    ()
end
```
```
File "test.ml", lines 4-11, characters 6-3:
 4 | ......struct
 5 |   let with_ ~f =
 6 |     let (use_f @ local unyielding) x =
 7 |       f x
 8 |     in
 9 |     let _ = use_f in
10 |     ()
11 | end
Error: Signature mismatch:
       Modules do not match:
         sig val with_ : f:('a -> 'b) -> unit end
       is not included in
         sig val with_ : f:('a -> 'a) @ local -> unit end
       Values do not match:
         val with_ : f:('a -> 'b) -> unit
       is not included in
         val with_ : f:('a -> 'a) @ local -> unit
       The type f:('a -> 'a) -> unit is not compatible with the type
         f:('a -> 'a) @ local -> unit
       File "test.ml", line 2, characters 2-42: Expected declaration
       File "test.ml", line 5, characters 6-11: Actual declaration
```

This PR fixes the printing of the modes so that they print the
implementation modes as close as possible to the interface, highlighting
the difference between the two.
```
Lines 4-11, characters 6-3:
 4 | ......struct
 5 |   let with_ ~f =
 6 |     let (use_f @ local unyielding) x =
 7 |       f x
 8 |     in
 9 |     let _ = use_f in
10 |     ()
11 | end
Error: Signature mismatch:
       Modules do not match:
         sig val with_ : f:('a -> 'b) @ local unyielding -> unit end
       is not included in
         sig val with_ : f:('a -> 'a) @ local -> unit end
       Values do not match:
         val with_ : f:('a -> 'b) @ local unyielding -> unit
       is not included in
         val with_ : f:('a -> 'a) @ local -> unit
       The type "f:('a -> 'a) @ local unyielding -> unit"
       is not compatible with the type "f:('a -> 'a) @ local -> unit"
```

**Changes in this PR:**
- Make sure hints are not erased in `subst`. This is not needed here,
but is a precursor to eventually print hint chains
- When a mode inclusion check fails during `moregen`, the implementation
mode gets zapped to be as close as possible to the interface mode. This
is so that it does not get zapped to legacy when printed, leading to
very strange error messages
- Print the mode error message at the end

**Further improvements still missing**
- Currently the hint explanation chain gets cut off in
`split_function_ty`. The mode error message is therefore often not very
informative, and the user has to manually annotate the implementation to
get proper hints. In the future, we will need to create a new hint morph
add use them in `split_function_ty` to preserve hint chains across `l2r`
transformations, and change the printing of module inclusion errors to
print the hint chain.