Support layout-polymorphic records and variants
Previously, when Lambda tried to determine the representation of a record or
variant constructor, `finalize_instantiated_shape` would raise
`Layout_poly_variable_representation` if it encountered a non-concrete sort.

For example, the following program

```
type ('a : any) maybe = Nuthin | Gimme of 'a

let poly_ map f = function
| Nuthin -> Nuthin
| Gimme x -> Gimme (f x)
```

gives

```
Error: The representation of this record or variant depends on a
       layout-polymorphic type, which is not yet supported.
```

This commit adds support for layout-polymorphic records and variants. When
`finalize_instantiated_shape` encounters a generalized sort variable, it
translates it to a splice variable to be evaluated away in Slambda.

As a consequence, certain representation checks that used to come 'early' in the
compiler need to be delayed for layout-polymorphic shapes, since we don't know
the runtime layout of lpoly fields until after Slambda. These checks are:

1. The mixed block value prefix length check.
2. The mixed block index gap overflow check.

After discussing with Ryan, I decided to leave the 'early' checks in place for
non-lpoly shapes in order to provide an earlier error message where possible.
We might instead decide instead to just do the check once, after Slambda.

Also note that construction of layout-polymorphic blocks is not currently
supported inside of a recursive definition.

This commit also adds tests exercising some basic layout-poly records and
constructors, and the two checks mentioned above.

(cherry picked from commit aaee25d5f7d2a76036bac524df9066e51a7252d4)