Introduce an intermediate Reaper file format with test data, and read/write from it (#6638)
Adds magic number plumbing for a new file format, CMR, with code to read
and write a plain string (placeholder) from these files. The file is
created when `-support-lto` is passed, and loaded when passed to
`-reaper-rebuild`:

```
$ ocamlopt.opt -c test.ml -flambda2-reaper -support-lto
LTO enabled

$ ocamlopt.opt -reaper-rebuild test.cmr
Loaded data from CMR file: Hello, cmr!
>> Fatal error: cmr_to_cmm unimplemented
...
```