Add support for atomic block indices
Currently, one cannot take the block index of an atomic record field:

```
type t = { mutable x : int [@atomic] }
let i = (.x)
```

```
2 | let i = (.x)
            ^^^^
Error: Block indices do not yet support [@atomic] record fields.
```

This PR introduces `atomic_idx`, a predef type representing an index to an
atomic record field. Users can create an atomic index using the usual block
access syntax. They can read and write the underlying data atomically using
`Idx_atomic.get` and `Idx_atomic.set` in `Stdlib_stable`.

Some considerations:

- We support creating atomic indices to any atomic field in both boxed and mixed
  records. Note that atomic non-value fields remain unsupported.
  - This includes singleton unboxed records, which have kind `value` and
    are allowed to be atomic:

```
type inner = { y: int }
type outer = { mutable x: inner# [@atomic] }

let idx : (outer, inner) idx_atomic = (.x.#y)
```

- We do not support atomic index deepening. This is because fields with unboxed
  types cannot be atomic, with the just-discussed exception of singleton
  unboxed records.
- This PR does not implement atomic pointer primitives (get/set ptr/ext_ptr),
  since these primitives can be used to write off-heap values, which aren't
  supported well by existing atomic primitives.

Testing:
========
- Typing tests for `idx_atomic`.
- `caml_modify`-style tests that ensure we skip runtime calls when setting
immediates atomically.
- Native/bytecode tests reading/writing atomic fields through their indices.

Note that I did **not** update `records-and-block-indices/test_generation.ml` to
randomly generate `idx_atomic` tests. The existing test generation code relies
on certain language features (pattern matches, functional updates) that work
differently (or not at all) for atomic record fields. Like `idx_imm` (which is
also not exercised in the randomly generated tests),
`idx_atomic` shares much of its implementation with `idx_mut`, which is covered.
I think the manual testing in `idx_atomic.ml` but am happy to discuss with reviewers.