Support layout-polymorphic records and variants (#7152)
Previously, when Lambda tried to determine the representation of a
record or
variant constructor, `finalize_instantiated_shape` would raise
`Layout_poly_variable_representation` if it encountered a non-concrete
sort.

For example, the following program

```
type ('a : any) maybe = Nuthin | Gimme of 'a

let poly_ map f = function
| Nuthin -> Nuthin
| Gimme x -> Gimme (f x)
```

gives

```
Error: The representation of this record or variant depends on a
       layout-polymorphic type, which is not yet supported.
```

This PR adds support for layout-polymorphic records and variants. When
`finalize_instantiated_shape` encounters a generalized sort variable, it
translates it to a splice variable to be evaluated away in Slambda.

As a consequence, certain representation checks that used to come
'early' in the
compiler need to be delayed for layout-polymorphic shapes, since we
don't know
the runtime layout of lpoly fields until after Slambda. These checks
are:

1. The mixed block value prefix length check.
2. The mixed block index gap overflow check.

After discussing with Ryan, I decided to leave the 'early' checks in
place for
non-lpoly shapes in order to provide an earlier error message where
possible.
We might instead decide instead to just do the check once, after
Slambda.

Also note that construction of layout-polymorphic blocks is not
currently
supported inside of a recursive definition.

This PR also adds tests exercising some basic layout-poly records and
constructors, and the two checks mentioned above.

### Review
I split this PR into four commits. The first three are preparatory
refactors, and the last one is a behavioral change.
1. Refactor: Rename the Lambda `constructor_shape` constructors. They
would otherwise collide with the `constructor_representation`
constructors that I add in the next commit.
2. Refactor: Move `finalize_instantiated_shape` and friends to
`Typeopt`. I think this is a better place for them, because they depend
on both `typing/` types and `lambda/` types.
3. Refactor: Finalize record/constructor representation to `lambda/`
types instead of `typing/` types. The goal here is to migrate to shapes
that can carry splice variables.
4. Behavioral change: Support layout-polymorphic records and variants by
translating generalized sort variables into splice variables.

I then added two more commits for Merlin updates:

1. Import Merlin changes.
2. AI-assisted fix-up of Merlin changes. Unfortunately, since `Typedecl`
still calls `finalize_record_representation`, Merlin needs to know about
the new Lambda types; we copy them over.