Annotation hint (#6249)
This PR creates a new leaf hint for annotations. If a mode can be
explained by an annotation, the hint will now print the location of the
annotation.

For example: 
```
let use_uncontended (x @ uncontended) = ()
let foo (x @ contended) = use_uncontended x

File "test.ml", line 2, characters 42-43:
2 | let foo (x @ contended) = use_uncontended x
                                              ^
Error: This value is contended (file "test.ml", line 2, characters 13-22)
       but is expected to be uncontended (file "test.ml", line 1, characters 25-36).
```

--- 

Updates from @gavinleroy, this PR no longer uses the annotation hint in
error messages, but the leaf hint is still added so that we can use the
information in the interactive diagnostics. I've updates things in two
ways:

1. The new `Annotation` hint does not add information to the textual
error messages. This was deemed too verbose previously and we intend to
use this information in only the interactive errors.
2. Instead of holding a single `Location.t`, the `Annotation`
constructor takes a pointer the *specific annotation* that introduced
the bound. This is more helpful when implied bounds are involved,
because we can point to the exact axis that implied the bound rather
than saying "the bound was annotated here <loc>" when in fact it wasn't.

---------

Co-authored-by: Gavin Gray <gavinleroy@gmail.com>