refactor: avoid redundant type_jkind while specializing peek/poke primitives
This change is intended as a pure refactor.

In `lambda/`, calling `type_sort` on a type whose sort contains generalized
sort variables is not safe, even with `fixed:true`. `type_sort` unifies the
generic sort variable with a fresh one, destroying the invariant that a
generalized sort variable is a root. The broken invariant is discovered when we
later try to convert the `Sort.Const.t` to a Lambda shape:

```
>> Fatal error: Slambdaident.of_sort_var: not a root
```

To avoid this issue, in #7243 I added a guard to peek_or_poke_layout_from_type
that explicitly rejects layouts carrying generalized variables. But this check
led to us calling `type_jkind` redundantly.

This change eliminates that redundant call. Rather than call `type_sort`, we use
existing lpoly machinery to convert from a type to its Lambda shape.
(We retain the same error message, since some work is necessary after Slambda
eval if we actually want peek/poke to support layout-polymorphic arguments.)

I mainly raise this PR to demonstrate one way to avoid calls to `type_sort`
outside the typechecker.